### PR TITLE
Add ramsalt-module type and installer-path by default

### PR DESCRIPTION
**Pull request by doxigo**
We have multiple ramsalt-module right now, would be nice to support it by default in our template

### CODE REVIEW

**Comment by szeidler** [comment]
Do you have some examples? I remember that the `ramsaltmedia-module` naming always has been under debate, because we use it also for non ramsaltmedia things.

**Comment by doxigo** [comment]
@szeidler ie. `rm_gutenberg_media` module, that's a general `ramsalt` module

**Review by szeidler — CHANGES_REQUESTED** [review]
We would need to add the folder to the general gitignore over at https://github.com/ramsalt/drupal-scaffold/blob/master/assets/gitignore-additions . Otherwise those files would get tracked by default.

**Comment by szeidler** [comment]
Still pending the requested changes

**Comment by doxigo** [comment]
Created the [PR](https://github.com/ramsalt/drupal-scaffold/pull/26) here

**Review by szeidler — APPROVED** [review]

**Pull request merged**
