### PR TITLE
Add default useful modules.

### PR DESCRIPTION
**Pull request by esolitos**
I think it would make sense to have a boilerplate with modules we use virtually on all sites.

### CODE REVIEW

**Comment by szeidler** [comment]
I like the idea. Although it's always hard to maintain the list.

I personally prefer [Select2](https://www.drupal.org/project/select2) over Chosen. The library itself feels more supported for me. And it recently got into Thunder, too (okay, that might not be an real argument :))

As mentioned in slack. I'm surprised to see a module here, that I don't now: drupal/amswap. But I would like to hear from the ones, that used it, how it works. Just for this, this PR is valuable :)

**Comment by Sadeghbayan** [comment]
What about [Menu attributes](https://www.drupal.org/project/menu_attributes) ?

**Comment by esolitos** [comment]
@Sadeghbayan
Well, regarding `menu_attributes`, first of all because it simply doesn't have a Drupal 8 release. :) 

@szeidler 
> Although it's always hard to maintain the list

Yes, that is true, to help in this we should keep the list to the minimum, maybe it's already to large?

Regarding chosen: I have no preference between select2 and chosen, If you think it's better I'll trust you on this.

**Comment by esolitos** [comment]
So, what should we do?
The check failures are deprecations coming from ctools it seems.

**Comment by vegardjo** [comment]
Marlon will rebase it

**Pull request closed without merging**
